### PR TITLE
feat(#319): add char + weapon run counter to banner

### PR DESCRIPTION
**Pull request by benlei**
This bit of information will be helpful to see how many times a char has ben run without needing to manually count the # of icons.

For the ticket I created (#319)

5 stars characters:
image

4 stars characters:
image

5 star weapons:
image

4 star weapons:
image

### CODE REVIEW

**Comment by benlei** [comment]
> Maybe exclude the personages from the standard banner ?

I'm not sure what you mean by "personages". Can you elaborate?

**Comment by orkeilius** [comment]
*character (i'm stupid)

**Comment by benlei** [comment]
I guess if @MadeBaruna requests for it, I can try to do it (or MadeBaruna can edit my PR directly). That being said I'm not aware of any way to differentiate a limited character from a standard one. 

I think having it as-is is good in that it's fairly simple.

**Comment by orkeilius** [comment]
That true, but having a way to filter character that will never be reroll is a good feature to have something more clear. 

If someone implements this, the most simple way is probably to hard code it. Because the standard banner don't change  often anyway

(That just a suggestion you don't need to implement yourself)

**Pull request closed without merging**
