### PR TITLE
feature - 5 star rate up winning rate

### LINKED ISSUE #247: feature - 5 star rate up winning rate
It's nice to have, is it possible to add a visible 5 star winning rate to show the rate of wining the limited banner character? 

For example on my character pulls below, I have gotten 37x of 5 star character, but there are 13x of 5 star wish losing the pity. \
So my winning rate is `(37-13) / 37` -> `64.86%` . Or showing like `limited/5 star: 24/37` is also ok

### PR DESCRIPTION
**Pull request by edwardccg**
PR to close #247 

### Purpose

- To show the total number of 5 stars obtained are the featured character/weapon during the banner period.
- Also to show an icon to indicate it's a rate up character/weapon.

Off Topics: Always sad to see the 4x Qiqi there :(

### Before
**Character Event:**

**Weapon Event:**

### After
**Character Event:**

**Weapon Event:**

### CODE REVIEW

**Comment by edwardccg** [comment]
Another option is use the round icon, probably looks better?
image

**Comment by MadeBaruna** [comment]
Hello thanks for the PR, will check it soon

**Comment by edwardccg** [comment]
@MadeBaruna , any update for this?

**Comment by MadeBaruna** [comment]
Hey sorry, this implementation is kinda heavy (it loops every item), I need to make some modification first

**Comment by toadsworth-jr** [comment]
You closed this as incomplete...
But that's okay.

**Comment by MadeBaruna** [comment]
yeah? I already add the feature with that commit, the code is very different so I can't continue this PR

**Pull request closed without merging**
