### PR TITLE
Add Korean locale phrases.

### PR DESCRIPTION
**Pull request by Hatser**
1. Added Korean translation of most of the locale phrases.

2. Added South Korean flag SVG file _static/images/locales/ko.svg_

3. To solve the problem of word order difference between other languages and Korean, I changed a few logics including uses of i18n function(_$t_).
[_src/routes/_index/banner.svelte_](https://github.com/MadeBaruna/paimon-moe/compare/main...Hatser:main#diff-841d6effd9a068b7b8ea8e62fb848a068e72faab5c0ec3fc5ebb1933a2ea3579) and [_src/routes/calculator/index.svelte_](https://github.com/MadeBaruna/paimon-moe/compare/main...Hatser:main#diff-2b33ebabba17a4b2846878fe64b83c31a9c2e79deabcb6f4ef6810463dd38484)
If someone tries to translate in Japanese, It will help.

4. Edited some time format logics in resin timer.
I don't know why but it was forcing users to use 'en' or 'id' locale format.
you can checkout about the changes [_here_](https://github.com/MadeBaruna/paimon-moe/compare/main...Hatser:main#diff-ca7bd96ac387bafeddd6330359391c04a27f434f5b5e2b72f8c7677a0fbd2ca6) and [_here_](https://github.com/MadeBaruna/paimon-moe/compare/main...Hatser:main#diff-b7802a3d2865af75f4320c471603c5a5327c7be9deb1a852a84952ecb7fae946)

### CODE REVIEW

**Comment by Hatser** [comment]
Unsolved problem:

_wish.help.howto.press_ and _wish.help.howto.whenYouGet_, _wish.help.howto.p1_ and _wish.help.howto.and_ needed to be merged to follow Korean syntax(word order) but button-square and star-icon styling block me to try it.

**What I tried to do:**
```svelte
    <p class="mb-2">
      {@html $t('wish.help.howto.pressWhenYouGet', {
        values: {
          button: '<b class="rounded-lg px-2 py-1 border-white border inline-flex items-center">+1</b>',
          rarity: `<span class="inline-flex items-center">3<${Icon} path=${mdiStar} size=${0.7} /></span>`,
        },
      })}
    </p>
    <p class="mb-2">
      {@html $t('wish.help.howto.pressWhenYouGet', {
        values: {
          button: `<b class="rounded-lg px-2 py-1 border-white border inline-flex items-center">Get 4<svelte:options tag="Icon" path=${mdiStar} size=${0.7} /></b>`,
          rarity: `<span class="inline-flex items-center">4<Icon path=${mdiStar} size=${0.7} /></span>`,
        },
      })}
    </p>
    <p class="mb-2">
      {@html $t('wish.help.howto.pressWhenYouGet', {
        values: {
          button: `<b class="rounded-lg px-2 py-1 border-white border inline-flex items-center">Get 5<Icon path=${mdiStar} size=${0.7} /></b>`,
          rarity: `<span class="inline-flex items-center">5<Icon path=${mdiStar} size=${0.7} /></span>`,
        },
      })}
    </p>
    <p class="text-gray-400">
      {@html $t('wish.help.howto._p1', {
        values: {
          r1: `<span class="inline-flex items-center">5<Icon path=${mdiStar} size=${0.7} /></span>`,
          r2: `<span class="inline-flex items-center">4<Icon path=${mdiStar} size=${0.7} /></span>`,
        },
      })}
    </p>
```

when en.json has:
```json
        "pressWhenYouGet": "Press {button} when you get {rarity}",
        "_p1": "It will automatically add the lifetime pulls,",
```

**but <Icon /> component couldn't be rendered in that way.**

and to do this, it requires [an additional compiler-setting](https://stackoverflow.com/questions/60529034/svelte-custom-element-api).

**Comment by MadeBaruna** [comment]
Hey thank you very much for the PR!
For the problem maybe should just change the star icon with simple star character (★)

**Comment by Hatser** [comment]
Edited _WishCounterHowToModal.svelte_, 

Changed some star Icon components into a normal ★ character.

and Modified locale files according to the changes.

**Comment by Hatser** [comment]
Previous PR was based on old(before I translate things...) locale files.

fixed it.

**Pull request merged**
