### PR TITLE
Update Russian locale

### PR DESCRIPTION
**Pull request by SecondThundeR**
Add locale for TCG
Add some missing keys
Rephrase donate.crypto string
Remove extra exclamation mark in "comingsoon" string

### CODE REVIEW

**Comment by lakejason0** [comment]
Please submit translation through Crowdin.

**Comment by lakejason0** [comment]
https://crowdin.com/project/paimon-moe

**Comment by SecondThundeR** [comment]
Oh, I see, thanks for the link, I guess this PR can be closed for now?

**Comment by lakejason0** [comment]
> Oh, I see, thanks for the link, I guess this PR can be closed for now?

Sure.

**Pull request closed without merging**
